language: python
python:
  - 3.5.2
 
  
# command to install dependencies

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls
  - pip install nose2

# command to run tests
script:
  - coverage run --source=lib -m nose2.__main__ -v    



after_success:
  - coveralls


